### ISSUE TITLE
Posts and Comments data delay?

### ISSUE THREAD

**Issue by oflyhigh** [SteemData/steemdata-mongo#1]
Hi @Netherdrake ,

First, thank you very much for provide this amazing service: steemdata.com.

But in recent days, I could not fetch fresh posts and comments data.
There seems some delay of those two collections/tables.

For example:
I try run this command in python shell: 
>>> posts=db ['Posts'].find({'created': {'$gte': dateutil.parser.parse('2017-07-2 00:00:00.000Z')}})
>>> print(posts.count())
0
And, Now, It's 2017-07-03 13:11 (UTC +0)

Could you look into this issue? Thank you very much for your help.

**Comment by Netherdrake** [comment]
I'll be deploying our own steemd node to fix the lag.
