### ISSUE TITLE
Posts & Comments out of sync for over a day

### ISSUE THREAD

**Issue by therealwolf42** [SteemData/steemdata-mongo#5]
Hey furion,

steemdata is really great and my load time and quering of Posts has been tremendously reduced through it. But the problem is that it is out of sync since yesterday. 

Is this something you are aware of? Is that because of node lag?

The project I'm working on kind of depends on the freshness of posts. So is there something I could do?

Thank you!

**Comment by oferitz** [comment]
@Netherdrake seems like there is no new data since 23.11
